config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # FIXME: Signed in / out
  root to: 'jobs#index'

  resources :secrets

  resources :jobs do
    member do
      get :download
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  has_one_attached :upload
  has_one :run

  validates :title, presence: true
  validates :description, presence: true

  def complete?
    run.present? && run.completed_at
  end

  def to_downloadable
    d = Download.new(self)

    d.result
  end

  class Download
    ERBPayload = Struct.new(:name, :description, :text)

    def initialize(j)
      @payload = ERBPayload.new(
        j.title,
        j.description,
        j.run&.resolved_text
      )
    end

    def result
      erb_template_fp = Rails.root.join('app', 'views', 'jobs', 'download.erb.txt')

      erb = ERB.new(File.read(erb_template_fp))

      erb.result(get_binding)
    end

    # disable:rubocop
    def get_binding
      binding
    end
    # enable:rubocop
  end
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  has_many :secrets

  def openai_credentials
    secrets.open_ai&.first
  end

  def gcp_credentials
    secrets.gcp&.first
  end
end

app/models/run.rb
# frozen_string_literal: true

class Run < ApplicationRecord
  belongs_to :job

  def complete?
    completed_at.present?
  end
end

app/models/secret.rb
# frozen_string_literal: true

class Secret < ApplicationRecord
  lockbox_encrypts :blob

  belongs_to :profile

  enum vendors: {
    open_ai: 'open_ai',
    gcp: 'gcp'
  }

  validate :name_is_unique

  module Vendor
    OpenAI = 'Open AI'
    GoogleCloudPlatform = 'Google Cloud Platform'

    def self.decorated_name(val)
      case val
      when :open_ai
        OpenAI
      when :gcp
        GoogleCloudPlatform
      end
    end
  end

  def vendor_name
    Vendor.decorated_name(vendor.to_sym)
  end

  private

  def name_is_unique
    errors.add(:name, 'Profile has secret with same name already') if profile.secrets.exists?(name:)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def current_profile?
    current_profile.present?
  end

  def current_profile
    # TODO
    if session[:profile_id]
      @current_profile = Profile.find(session[:profile_id])
      @current_profile
    else
      # FIXME:
      Profile.first
    end
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  before_action :set_job, only: %i[show download]

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def download
    dl = compose_job_download(@job)

    send_data(dl[:data], filename: dl[:filename], disposition: 'attachment')
  end

  def show; end

  def create
    @j = Job.new(job_params)

    if @j.save
      redirect_to @j, success: 'job created'
    else
      flash.now[:warning] = "Failed to create job: #{@j.errors.full_messages.join('. ')}"

      render 'new'
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :upload)
  end

  def set_job
    @job = Job.find(params[:id])
  end

  def compose_job_download(j)
    digest = Digest::MD5.hexdigest("#{j.title}_#{Time.now.to_i}")

    {
      data: j.to_downloadable,
      filename: "#{digest}_#{j.title}.txt"
    }
  end
end

app/controllers/secrets_controller.rb
# frozen_string_literal: true

class SecretsController < ApplicationController
  before_action :set_secret, only: [:destroy]

  def new
    @secret = current_profile.secrets.build
  end

  def index
    @secrets = current_profile.secrets
  end

  def create
    @secret = current_profile.secrets.build(secret_params)

    respond_to do |format|
      if @secret.save
        format.html { redirect_to secrets_path, success: 'Added' }
      else
        format.html { redirect_to new_secret_path, warning: @secret.errors.full_messages.first }
      end
    end
  end

  def destroy
    @secret.destroy!

    redirect_to secrets_path, success: "Secret #{@secret.name} was removed"
  end

  private

  def secret_params
    params.require(:secret).permit(:name, :vendor, :blob)
  end

  def set_secret
    @secret = Secret.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def signed_in?
    # FIXME
    true
  end
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true

module JobsHelper
end

app/helpers/secrets_helper.rb
# frozen_string_literal: true

module SecretsHelper
  def pretty_vendors_list
    Secret.vendors.values.map do |v|
      [
        Secret::Vendor.decorated_name(v.to_sym),
        v
      ]
    end
  end
end

app/views/jobs/_card.html.erb
<div class="card" style="20 rem; border-style: solid;">
  <div class="card-body">
    <p class="card-text">
      <%= link_to job.title, job_path(job) %>
    </p>

    <div>
      <!-- corner buttons -->
    </div>
  </div>
</div>

app/views/jobs/_form.html.erb
<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title, class: 'form-control' %>
  <small id="title_help" class="form-text text-muted">The title of the job</small>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.text_field :description, class: 'form-control' %>
  <small id="description_help" class="form-text text-muted">Give a quick description to remember later</small>
</div>

<div class="form-group">
  <%= form.label :upload %>
  <%= form.file_field :upload, class: 'form-control', accept: 'image/png,image/jpeg' %>
  <small id="upload_help" class="form-text text-muted">Upload your document</small>
</div>

<div class="submit-field">
  <%= form.submit "Create", class: "btn btn-primary mt-2"%>
</div>

app/views/jobs/_grid.html.erb
<div class="row">
  <% if jobs.any? %>
    <% jobs.in_groups_of(4).each do |jgroup| %>
      <div class="row">
        <% jgroup.compact.each do |j| %>
          <div class="col-sm-3">
            <%= render partial: "/jobs/card", locals: { job: j } %>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= link_to "Create new job", new_job_path, class: 'mt-4' %>

  <% end %>
</div>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/index.html.erb
<div class="mt-3">
  <div class="row">
    <h1>My Docs</h1>
    <div class="content-feed">
      <% if @jobs.empty? %>
        <%= link_to "Create new job", new_job_path %>
      <% else %>
        <%= render partial: "/jobs/grid", locals: { jobs: @jobs } %>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<h1>Create new job</h1>
<%= form_with(model: @job) do |form| %>
  <%= render partial: "/jobs/form", object: form%>
<% end %>

app/views/jobs/show.html.erb
<div class="mt-3">
  <h1> <%= @job.title %> </h1>
  <p> <%= @job.description %> </h2>

  <!-- split -->
  <div class="row">
    <div class="col-md-6"> 
      <!-- Uploaded image -->
      <%= image_tag(@job.upload, class: 'img-fluid')%>
    </div>
    <div class="col-md-6"> 
      <div> 
        <h2>Text Detected</h2>
        <!-- TODO: has text -->
        <%= @job.run&.resolved_text.present? ? @job.run.resolved_text : "No resolved result" %>
      </div>

      <div class="row mt-3">
        <div class="col-md-6">
          <%= link_to "Save Results", 
            download_job_path(@job), 
            remote: true %>
          </div> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trampoline</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= render partial: 'shared/notices' %>

    <div class="container mx-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/secrets/_form.html.erb
<%= form_with(model: @secret) do |f| %>
  <div class="form-group my-2">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <small id="name_help" class="form-text text-muted">The name of this credential</small>
  </div>

  <div class="form-group my-2">
    <%= f.label :blob %>
    <%= f.text_field :blob, class: 'form-control' %>
    <small id="blob_help" class="form-text text-muted">The credential value</small>
  </div>

  <div class="form-group my-2">
    <%= f.label :vendor_id %>
    <small id="vendor_help" class="form-text text-muted">The vendor value</small>

    <div class="form-group">
      <%= f.select :vendor, pretty_vendors_list %>
    </div>
  </div>

  <%= f.submit "Add", class: "btn btn-success"%>
<%end%>

app/views/secrets/_secret.html.erb
<div class="card mt-3">
  <div class="card-body">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="card-title"><%= secret.name %> </h5>
    </div>
    <h6 class='card-subtitle mb-2 text-muted'>
      <%= secret.vendor_name %> Secret
    </h6>
    <form>
      <fieldset disabled>
        <div class="form-group">
          <label> Blob </label>
          <input class="form-control" value="**************"/>
        </div>
      </fieldset>
    </form>
  </div>
  <div class="card-footer text-muted">
    <div class="row">
      <div class="col">
        <p>
          Added <%= time_ago_in_words(secret.created_at) %> ago 
        </p>
      </div>
      <div class="col">
        <%= link_to "Delete", 
          secret_path(secret), 
          data: { turbo_method: :delete, confirm: "Are you sure you want to delete this?"},
          class: 'btn btn-danger float-right ml-3'
        %>
      </div>
    </div>
  </div>
</div>

app/views/secrets/create.html.erb
<h1>Secrets#create</h1>
<p>Find me in app/views/secrets/create.html.erb</p>

app/views/secrets/index.html.erb
<div class="container mt-3">
  <h1 class=''>Secrets</h1>
  <section name="secrets" class="py-3">
    <% if @secrets.empty? %>
      <div class="py-3">
        <p class="text-muted"> No secrets. You can add one <%= link_to "here", new_secret_path %> </p>
      </div>
    <% else %>
      <%= link_to "Add New Secret", new_secret_path %> </p>
      <!-- Name of the partial is important, must be keys if you want to use collection -->
      <%= render partial: 'secret', collection: @secrets %>
    <% end %>
  </section>
</div>

app/views/secrets/new.html.erb
<div class="container mt-3">
  <h2 class="title"> Add Secret</h2>
  <%= render 'form'%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container mx-auto">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand text-primary" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" i="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <% if signed_in? %>
          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              You
            <% end %>

            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
              <%= link_to "Secrets", secrets_path, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<div id="container mx-auto">
  <% flash.each do |name, msg| %>
    <div class="alert alert-dismissible fade show">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>